// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MoleculeConvertRequest
 * Request to convert molecule between formats.
 */
export type MoleculeConvertRequest = {
    /**
     * Input Format
     */
    input_format: 'smiles' | 'pdb' | 'sdf' | 'mol2' | 'xyz';
    /**
     * Output Format
     */
    output_format: 'smiles' | 'pdb' | 'sdf' | 'mol2' | 'xyz';
    /**
     * Data
     * Molecule data in input format
     */
    data: string;
};

/**
 * MoleculeConvertResponse
 * Response from molecule conversion.
 */
export type MoleculeConvertResponse = {
    /**
     * Output Format
     */
    output_format: string;
    /**
     * Data
     */
    data: string;
    molecule_info: MoleculeInfo;
};

/**
 * MoleculeInfo
 * Molecular information.
 */
export type MoleculeInfo = {
    /**
     * Formula
     */
    formula: string;
    /**
     * Molecular Weight
     */
    molecular_weight: number;
    /**
     * Num Atoms
     */
    num_atoms: number;
    /**
     * Num Bonds
     */
    num_bonds: number;
    /**
     * Num Heavy Atoms
     */
    num_heavy_atoms?: number;
    /**
     * Num Rotatable Bonds
     */
    num_rotatable_bonds?: number;
    /**
     * Logp
     */
    logp?: number;
};

/**
 * MoleculePropertiesRequest
 * Request to calculate molecular properties.
 */
export type MoleculePropertiesRequest = {
    /**
     * Smiles
     * SMILES string of molecule
     */
    smiles: string;
};

/**
 * MoleculePropertiesResponse
 * Response with molecular properties.
 */
export type MoleculePropertiesResponse = {
    /**
     * Smiles
     */
    smiles: string;
    properties: MoleculeInfo;
};

/**
 * MoleculeValidateRequest
 * Request to validate molecule structure.
 */
export type MoleculeValidateRequest = {
    /**
     * Smiles
     * SMILES string to validate
     */
    smiles: string;
};

/**
 * MoleculeValidateResponse
 * Response from molecule validation.
 */
export type MoleculeValidateResponse = {
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Smiles
     */
    smiles: string;
    /**
     * Canonical Smiles
     */
    canonical_smiles?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ConvertMoleculeApiMoleculesConvertPostData = {
    body: MoleculeConvertRequest;
    path?: never;
    query?: never;
    url: '/api/molecules/convert';
};

export type ConvertMoleculeApiMoleculesConvertPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertMoleculeApiMoleculesConvertPostError = ConvertMoleculeApiMoleculesConvertPostErrors[keyof ConvertMoleculeApiMoleculesConvertPostErrors];

export type ConvertMoleculeApiMoleculesConvertPostResponses = {
    /**
     * Successful Response
     */
    200: MoleculeConvertResponse;
};

export type ConvertMoleculeApiMoleculesConvertPostResponse = ConvertMoleculeApiMoleculesConvertPostResponses[keyof ConvertMoleculeApiMoleculesConvertPostResponses];

export type ValidateMoleculeApiMoleculesValidatePostData = {
    body: MoleculeValidateRequest;
    path?: never;
    query?: never;
    url: '/api/molecules/validate';
};

export type ValidateMoleculeApiMoleculesValidatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateMoleculeApiMoleculesValidatePostError = ValidateMoleculeApiMoleculesValidatePostErrors[keyof ValidateMoleculeApiMoleculesValidatePostErrors];

export type ValidateMoleculeApiMoleculesValidatePostResponses = {
    /**
     * Successful Response
     */
    200: MoleculeValidateResponse;
};

export type ValidateMoleculeApiMoleculesValidatePostResponse = ValidateMoleculeApiMoleculesValidatePostResponses[keyof ValidateMoleculeApiMoleculesValidatePostResponses];

export type CalculatePropertiesApiMoleculesPropertiesPostData = {
    body: MoleculePropertiesRequest;
    path?: never;
    query?: never;
    url: '/api/molecules/properties';
};

export type CalculatePropertiesApiMoleculesPropertiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CalculatePropertiesApiMoleculesPropertiesPostError = CalculatePropertiesApiMoleculesPropertiesPostErrors[keyof CalculatePropertiesApiMoleculesPropertiesPostErrors];

export type CalculatePropertiesApiMoleculesPropertiesPostResponses = {
    /**
     * Successful Response
     */
    200: MoleculePropertiesResponse;
};

export type CalculatePropertiesApiMoleculesPropertiesPostResponse = CalculatePropertiesApiMoleculesPropertiesPostResponses[keyof CalculatePropertiesApiMoleculesPropertiesPostResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
